# Generated by Django 6.0.2 on 2026-06-06 14:24

import django.db.models.deletion
import django_cryptography.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('key_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gender_target', models.CharField(choices=[('MALE', 'Male Only'), ('FEMALE', 'Female Only'), ('MIXED', 'Mixed / Co-ed')], default='MIXED', max_length=10)),
                ('accommodation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('accommodation_logo_url', models.URLField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', django_cryptography.fields.encrypt(models.EmailField(max_length=254))),
                ('phone', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=15, null=True))),
                ('face_url', django_cryptography.fields.encrypt(models.URLField(blank=True, max_length=500, null=True))),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Administrator'), ('MODERATOR', 'System Moderator'), ('SUPPORT', 'Support Agent')], default='SUPERADMIN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_type', models.CharField(default='VENUE', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', django_cryptography.fields.encrypt(models.EmailField(max_length=254))),
                ('phone', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=15, null=True))),
                ('is_verified', models.BooleanField(default=False)),
                ('digital_verification_status', models.BooleanField(default=False)),
                ('manual_verification_status', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_signed', models.BooleanField(default=False)),
                ('contract_url', models.CharField(blank=True, max_length=500, null=True)),
                ('face_url', models.CharField(blank=True, max_length=500, null=True)),
                ('id_document_url', models.CharField(blank=True, max_length=500, null=True)),
                ('paystack_merchant_code', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_paystack_account', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalResponderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', django_cryptography.fields.encrypt(models.EmailField(max_length=254))),
                ('phone', django_cryptography.fields.encrypt(models.CharField(max_length=15))),
                ('face_url', django_cryptography.fields.encrypt(models.URLField(blank=True, max_length=500, null=True))),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('gender_target', models.CharField(choices=[('MALE', 'Male Only'), ('FEMALE', 'Female Only'), ('MIXED', 'Mixed / Co-ed')], default='MIXED', max_length=10)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.accommodation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendantProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('email', django_cryptography.fields.encrypt(models.EmailField(max_length=254))),
                ('phone', django_cryptography.fields.encrypt(models.CharField(max_length=15))),
                ('face_url', django_cryptography.fields.encrypt(models.URLField(blank=True, max_length=500, null=True))),
                ('role', models.CharField(choices=[('SECURITY', 'Security Officer'), ('ATTENDANT', 'Room Attendant'), ('GENERAL', 'General Staff')], default='ATTENDANT', max_length=20)),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to='api.landlordprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='api.landlordprofile'),
        ),
        migrations.CreateModel(
            name='LeavePermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('parent_cell_number', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_province', models.CharField(blank=True, choices=[('Gauteng', 'Gauteng'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Western Cape', 'Western Cape'), ('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Mpumalanga', 'Mpumalanga'), ('Limpopo', 'Limpopo'), ('North West', 'North West'), ('Northern Cape', 'Northern Cape'), ('Outside SA', 'Outside South Africa')], max_length=50, null=True)),
                ('destination_address', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('INSPECTING', 'Inspecting'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='REQUESTED', max_length=20)),
                ('qr_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assigned_attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to='api.attendantprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=50)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('is_damage_found', models.BooleanField(default=False)),
                ('damage_notes', models.TextField(blank=True, null=True)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inspections', to='api.attendantprofile')),
                ('permit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='api.leavepermit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('verification_status', models.BooleanField(default=False)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', django_cryptography.fields.encrypt(models.EmailField(max_length=254))),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('id_number', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=13, null=True))),
                ('phone', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=15, null=True))),
                ('face_url', models.URLField(blank=True, null=True)),
                ('id_document_url', models.CharField(blank=True, max_length=500, null=True)),
                ('proof_of_registration_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_cleared_for_exit', models.BooleanField(default=True)),
                ('requires_password_change', models.BooleanField(default=True)),
                ('applied_accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='api.accommodation')),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.landlordprofile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentMedicalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, null=True))),
                ('allergies', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('medical_conditions', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('emergency_contact_name', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('emergency_contact_phone', django_cryptography.fields.encrypt(models.CharField(max_length=20))),
                ('emergency_contact_relation', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='api.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('target_audience', models.CharField(default='all', max_length=50)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.adminprofile')),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.attendantprofile')),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.landlordprofile')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.medicalresponderprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='leavepermit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='api.studentprofile'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant_rating', models.IntegerField(blank=True, null=True)),
                ('custom_issue_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PENDING', 'Pending'), ('ATTENDING', 'Attending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('is_priority', models.BooleanField(default=False)),
                ('assigned_attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='api.attendantprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='api.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_gate_passes', to='api.attendantprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_passes', to='api.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Unassigned'), ('RESPONDING', 'Staff Responding'), ('RESOLVED', 'Resolved / Closed')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medicalresponderprofile')),
                ('reporting_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_emergencies', to='api.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessed_by_uid', models.CharField(max_length=128)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='api.emergencyreport')),
                ('student_accessed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_charge', to='api.issue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='api.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('gender_target', models.CharField(choices=[('MALE', 'Male Only'), ('FEMALE', 'Female Only'), ('MIXED', 'Mixed / Co-ed')], default='MIXED', max_length=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Units', to='api.block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.unit'),
        ),
    ]
