# Generated by Django 6.1 on 2026-08-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='is_active_subscriber',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='next_billing_date',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='trial_start_date',
        ),
        migrations.DeleteModel(
            name='LandlordSubscriptionLog',
        ),
    ]
