# Generated by Django 6.0.2 on 2026-06-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='emergency_type',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='situation_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
