# Generated by Django 6.0.2 on 2026-06-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emergencyreport_emergency_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalresponderprofile',
            name='role',
            field=models.CharField(default='responder', max_length=20),
        ),
    ]
