# Generated by Django 6.1 on 2026-08-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_landlordprofile_is_active_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='subscription_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
