# Generated by Django 6.0.2 on 2026-06-16 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medicalresponderprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='identified_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_emergencies', to='api.studentprofile'),
        ),
    ]
