# Generated by Django 6.0.2 on 2026-06-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emergencyreport_identified_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='face_encoding_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
