# Generated by Django 6.1 on 2026-09-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_accommodationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendantprofile',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accomodation_name', to='api.accommodation'),
        ),
        migrations.AddField(
            model_name='attendantprofile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='proof_of_funding_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attendantprofile',
            name='role',
            field=models.CharField(choices=[('SECURITY', 'Security Officer'), ('ATTENDANT', 'Room Attendant'), ('GENERAL', 'General Staff'), ('GENERAL', 'General Staff'), ('GENERAL', 'General Staff'), ('GENERAL', 'General Staff'), ('GENERAL', 'General Staff')], default='ATTENDANT', max_length=20),
        ),
    ]
