# Generated by Django 6.0.2 on 2026-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studentprofile_face_encoding_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='face_encoding_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
