# Generated by Django 6.0.2 on 2026-06-17 10:17

import django.db.models.deletion
import django_cryptography.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emergencyreport_face_encoding_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_contact', django_cryptography.fields.encrypt(models.CharField(max_length=20))),
                ('visitor_id_number', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('visitor_signature', models.TextField(blank=True, null=True)),
                ('qr_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Arrival'), ('SIGNED_IN', 'Signed In'), ('SIGNED_OUT', 'Signed Out')], default='PENDING', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='api.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_taken', models.CharField(max_length=50)),
                ('security_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.attendantprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
                ('visitor_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.visitorregister')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
