# Generated by Django 6.0.2 on 2026-06-22 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_visitorregister_visitorauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='reporting_attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendant_emergencies', to='api.attendantprofile'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='reporting_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_emergencies', to='api.studentprofile'),
        ),
    ]
