# Generated by Django 6.0.2 on 2026-06-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_emergencyreport_reporting_attendant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='seller_paystack_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
