"""
Django settings for memberssistant project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
import json
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

import firebase_admin
from firebase_admin import credentials 

BASE_DIR = Path(__file__).resolve().parent.parent 
load_dotenv(os.path.join(BASE_DIR, '.env')) 
SECRET_KEY = os.environ.get('SECRET_KEY') 
CRYPTOGRAPHY_KEY = os.environ.get('FERNET_KEY') 
DEBUG = os.environ.get('DEBUG', 'False') == 'True' 
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '*,127.0.0.1,localhost,172.20.10.8')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]
PAYSTACK_API_BASE = 'https://api.paystack.co'
# Application definition
INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  
    'rest_framework',
    'django_filters',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Parse CORS origins dynamically
# Example .env: CORS_ALLOWED_ORIGINS=https://myfrontend.com,https://www.myfrontend.com
cors_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://192.168.1.55:8000,http://172.20.10.8:8000,http://localhost:3000,http://127.0.0.1:3000')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',')]


ROOT_URLCONF = 'memberssistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'memberssistant.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY')
FIREBASE_STORAGE_BUCKET = os.environ.get('FIREBASE_STORAGE_BUCKET', 'membersisstant.firebasestorage.app')
FERNET_KEY = os.environ.get('FERNET_KEY') 
if not firebase_admin._apps:
    # 1. Try to load the entire JSON credentials from an environment variable first (Best for Cloud Secret Managers)
    firebase_creds_json = os.environ.get('FIREBASE_CREDENTIALS_JSON')
    
    if firebase_creds_json:
        creds_dict = json.loads(firebase_creds_json)
        cred = credentials.Certificate(creds_dict)
    else:
        # 2. Fallback to local file for development
        firebase_creds_path = os.environ.get('FIREBASE_CREDENTIALS_PATH', os.path.join(BASE_DIR, 'serviceAccountKey.json'))
        cred = credentials.Certificate(firebase_creds_path)
        
    # FIXED: You MUST pass the storageBucket in the options dictionary here
    firebase_admin.initialize_app(cred, {
        'storageBucket': FIREBASE_STORAGE_BUCKET
    })