// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-LvxuyDxwi_kfXmdxBOVHHguzx9_8LH4',
    appId: '1:160946575033:web:146564eedae473669bad68',
    messagingSenderId: '160946575033',
    projectId: 'membersisstant',
    authDomain: 'membersisstant.firebaseapp.com',
    storageBucket: 'membersisstant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRreOxtFsU9oKrd9XH0QTWGS3cr5COW4',
    appId: '1:160946575033:android:44d11af058962c319bad68',
    messagingSenderId: '160946575033',
    projectId: 'membersisstant',
    storageBucket: 'membersisstant.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApHQHQ_r4hDKuxDvn7M3bdwZV4SGaRlVU',
    appId: '1:160946575033:ios:1bb0ea8c49aa0bbf9bad68',
    messagingSenderId: '160946575033',
    projectId: 'membersisstant',
    storageBucket: 'membersisstant.firebasestorage.app',
    iosBundleId: 'com.mktechcloud.memberssistant',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApHQHQ_r4hDKuxDvn7M3bdwZV4SGaRlVU',
    appId: '1:160946575033:ios:e8835ed11d897c3b9bad68',
    messagingSenderId: '160946575033',
    projectId: 'membersisstant',
    storageBucket: 'membersisstant.firebasestorage.app',
    iosBundleId: 'com.example.mApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-LvxuyDxwi_kfXmdxBOVHHguzx9_8LH4',
    appId: '1:160946575033:web:2f04d8a369b109a19bad68',
    messagingSenderId: '160946575033',
    projectId: 'membersisstant',
    authDomain: 'membersisstant.firebaseapp.com',
    storageBucket: 'membersisstant.firebasestorage.app',
  );
}
