// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-LvxuyDxwi_kfXmdxBOVHHguzx9_8LH4',
    appId: '1:160946575033:web:02fe5f34b84a0feb9bad68',
    messagingSenderId: '160946575033',
    projectId: 'membersisstant',
    authDomain: 'membersisstant.firebaseapp.com',
    storageBucket: 'membersisstant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRreOxtFsU9oKrd9XH0QTWGS3cr5COW4',
    appId: '1:160946575033:android:b0b7ddd6935c70269bad68',
    messagingSenderId: '160946575033',
    projectId: 'membersisstant',
    storageBucket: 'membersisstant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApHQHQ_r4hDKuxDvn7M3bdwZV4SGaRlVU',
    appId: '1:160946575033:ios:e723fc52ad2cf2149bad68',
    messagingSenderId: '160946575033',
    projectId: 'membersisstant',
    storageBucket: 'membersisstant.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

}